
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [2]:
import numpy as np
array = np.arange(10) # 0 to 9
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [4]:
# reshape
# 3 x 3
array = np.arange(1,10)
array
reshaped_array = array.reshape((3,3))
reshaped_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Access the element at the second row, second column.


In [9]:
array_element = reshaped_array[1,1]
array_element

5

Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [10]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

addition = array1 + array2 # Addition
addition

sub = array1 - array2
sub 

mul = array1 * array2
mul

div = array1 / array2
div

array([0.25, 0.4 , 0.5 ])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [11]:
array = np.array([1,2,3,4,5])
array.sum()

15

In [12]:
array.mean()

3.0

In [13]:
array.std()

1.4142135623730951

Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [16]:
array = np.array([1,2,3,4,5,6])
new_array = array.reshape((2,3))
new_array

array([[1, 2, 3],
       [4, 5, 6]])


# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [20]:
array = np.random.randint(0 , 9 , size=(5,5))
array

array([[5, 8, 1, 5, 6],
       [5, 0, 7, 0, 0],
       [2, 6, 4, 0, 6],
       [3, 3, 7, 2, 4],
       [1, 0, 7, 4, 6]])

Replace all values in the sub-array with a specific value.


In [22]:
array[1:4,:] = 10
array

array([[ 5,  8,  1,  5,  6],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [ 1,  0,  7,  4,  6]])

Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [27]:
array = np.array([[1,2],[3,4],[5,6],[7,8]])
array[[1,3]]

array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [28]:
array = np.array([0,1,2])
array

array([0, 1, 2])

In [31]:
new_array = np.tile(array, (3,1))
new_array

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [35]:
array_1d = np.array([1,2,3])
array_1d + new_array

array([[1, 3, 5],
       [1, 3, 5],
       [1, 3, 5]])

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [38]:
random_array1 = np.random.randint(1,100, size=(3,3))
random_array2 = np.random.randint(1,100, size=(3,3))

# hstack vstack
concatenated_horizentally = np.hstack((random_array1,random_array2))
concatenated_horizentally 

array([[46, 73, 81, 61, 59, 27],
       [80, 92,  4, 16,  6, 44],
       [86, 28, 24, 21, 97, 18]])

In [39]:
#vstack
concatenated_vertically  = np.vstack((random_array1,random_array2))
concatenated_vertically

array([[46, 73, 81],
       [80, 92,  4],
       [86, 28, 24],
       [61, 59, 27],
       [16,  6, 44],
       [21, 97, 18]])

In [43]:
#Back to original form
#hsplit vsplit
splitted_array = np.hsplit(concatenated_horizentally,2)
splitted_array

[array([[46, 73, 81],
        [80, 92,  4],
        [86, 28, 24]]),
 array([[61, 59, 27],
        [16,  6, 44],
        [21, 97, 18]])]

In [45]:
random_array1 = splitted_array[0]
random_array1

array([[46, 73, 81],
       [80, 92,  4],
       [86, 28, 24]])

In [46]:
random_array2 = splitted_array[0]
random_array2

array([[46, 73, 81],
       [80, 92,  4],
       [86, 28, 24]])

In [44]:
#vsplit
splitted_array = np.vsplit(concatenated_vertically,2)
splitted_array

[array([[46, 73, 81],
        [80, 92,  4],
        [86, 28, 24]]),
 array([[61, 59, 27],
        [16,  6, 44],
        [21, 97, 18]])]

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [50]:
array  = np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])
count_dict = {}

for i in array:
    if i in count_dict:
        count_dict[i] += 1
    else:
        count_dict[i] = 1
    
count_dict


{1: 7, 2: 5, 3: 1, 4: 1, 5: 2, 6: 1, 8: 1, 9: 1, 22: 1, 21: 1}

In [51]:
mode = None
max_count = 0

for key, value in count_dict.items():
    if value > max_count:
        max_count = value
        mode = key

print(mode,max_count)

1 7


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

